uploads = []
outputs = []

[[generated]]
id = "Prus9vA3jkQMc4PiDLODa"
uri = "file://artifacts/find-lab/public/images/hero-bg.png"
type = "image"
title = "hero background nano lab"

[[generated]]
id = "l06_oF0C_okyuCFeud5-8"
uri = "file://artifacts/find-lab/public/images/pi-headshot.png"
type = "image"
title = "PI profile headshot"

[[generated]]
id = "G_krje50t_npo5VVRC6hM"
uri = "file://artifacts/find-lab/public/images/spintronics.png"
type = "image"
title = "spintronics illustration"

[[generated]]
id = "i--Asp260MNJ9BTKxSAlQ"
uri = "file://artifacts/find-lab/public/images/nanoelectronics.png"
type = "image"
title = "2D material nanoelectronics"
