// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/about-pi/InterfaceLab.tsx": () => import("../components/mockups/about-pi/InterfaceLab.tsx"),
  "./components/mockups/about-pi/ScholarlyDossier.tsx": () => import("../components/mockups/about-pi/ScholarlyDossier.tsx"),
  "./components/mockups/about-pi/WarmAcademic.tsx": () => import("../components/mockups/about-pi/WarmAcademic.tsx")
};
